# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Constant Learner
tagline:          'Online community of self-learners'
description:      'Tips, programs, plans, advice and more for self-learners. Made by <a href="https://twitter.com/tbatchelli" target="_blank">@tbathelli</a>.'
url:              http://tbatchelli.org

author:
  name:           'Toni Batchelli'
  url:            https://twitter.com/tbatchelli

paginate:         5

# Custom vars
version:          2.0.0
gems: [jekyll-paginate,jekyll-gist]

github:
  repo:           https://github.com/poole/hyde
